// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2NjBz-JIyB0W6wd85PCUmU6pexv3q_A',
    appId: '1:280554266468:web:552d691afbf13612e9a471',
    messagingSenderId: '280554266468',
    projectId: 'swasthya-saathi-app-50e96',
    authDomain: 'swasthya-saathi-app-50e96.firebaseapp.com',
    storageBucket: 'swasthya-saathi-app-50e96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLgDfzJlkuLZ_QIR2QlyWjaX2NTKpCu5k',
    appId: '1:280554266468:android:fdc9ba44dc913613e9a471',
    messagingSenderId: '280554266468',
    projectId: 'swasthya-saathi-app-50e96',
    storageBucket: 'swasthya-saathi-app-50e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9vI3Rh6QvhhmvPwxVdzB4buhlplWjdlc',
    appId: '1:280554266468:ios:2c46bc14e0b3a100e9a471',
    messagingSenderId: '280554266468',
    projectId: 'swasthya-saathi-app-50e96',
    storageBucket: 'swasthya-saathi-app-50e96.firebasestorage.app',
    iosBundleId: 'com.example.swasthyaSaathiFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9vI3Rh6QvhhmvPwxVdzB4buhlplWjdlc',
    appId: '1:280554266468:ios:2c46bc14e0b3a100e9a471',
    messagingSenderId: '280554266468',
    projectId: 'swasthya-saathi-app-50e96',
    storageBucket: 'swasthya-saathi-app-50e96.firebasestorage.app',
    iosBundleId: 'com.example.swasthyaSaathiFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2NjBz-JIyB0W6wd85PCUmU6pexv3q_A',
    appId: '1:280554266468:web:b990e7ff648d1965e9a471',
    messagingSenderId: '280554266468',
    projectId: 'swasthya-saathi-app-50e96',
    authDomain: 'swasthya-saathi-app-50e96.firebaseapp.com',
    storageBucket: 'swasthya-saathi-app-50e96.firebasestorage.app',
  );
}
